---
title: "Predict missing marker"
author: "Attila Gabor"
date: "4/5/2019"
output: html_document
---




```{r}
phospho_median <- readRDS("./data/raw_data/Median_allsamples_nocontrols_withcellcount.rds") %>% as_tibble()
reporters = c('IdU', 'p-CREB', 'p-STAT5', 'p-SRC', 'p-FAK', 'p-MEK', 'p-MAPKAPK2',
			  'p-S6K', 'p-MAP2K3', 'p-STAT1', 'p-p53', 'p-NFkB', 'p-p38', 'p-AMPK',
			  'p-Akt(Ser473)', 'p-ERK', 'CyclinB', 'p-GSK3b', 'GAPDH', 'p-MKK3-MKK6',
			  'p-PDPK1', 'p-BTK', 'p-p90RSK', 'p-SMAD23', 'p-STAT3', 'p-JNK',
			  'Ki-67', 'p-H3', 'p-S6', 'cleavedCas', 'p-MKK4', 'p-AKT(Thr308)',
			  'p-RB', 'p-4EBP1')
phospho_median <- phospho_median %>%
	rename(cellcount=`dmt$cellcount`) %>% 
	gather(key = "reporter",value="value", reporters) %>%
	mutate(reporter = make.names(reporter)) # %>%  # convert measured values to valid names to avoid later isssues 
	#select(-cellcount) # we dont need this info
phospho_median
```

# collect here the cell_lines that must not be giving away:
for phospo-ERK:
- T47D
- HCC1806



## 1. Phospho-ERK prediction

```{r}
cell_lines = as.character(unique(phospho_median$cell_line))

validation_cell_lines = c("T47D","HCC1806")
trainig_cell_lines = cell_lines[! cell_lines %in% validation_cell_lines]

# training data: <free to use>
# all reporters from training cell lines
pERK_training_data = phospho_median %>% 
	filter(cell_line %in% trainig_cell_lines) %>%
	spread(reporter,value)

# validation data: <KEEP>
# all reporters from validation cell lines
pERK_validation_data = phospho_median %>% 
	filter(cell_line %in% validation_cell_lines) %>%
	spread(reporter,value)

# training data: <use for predict validation data>
# all reporters, but p-ERK from validation cell lines
pERK_test_data = phospho_median %>% 
	filter(cell_line %in% validation_cell_lines) %>%
	spread(reporter,value) %>%
	select(-p.ERK)
```

## 1.1 From same experiments and same time





